version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-2fa-app:latest
    container_name: 2fa-app
    ports:
      - "8080:8080"
    environment:
      - TZ=UTC
    volumes:
      - seed-data:/data
      - cron-output:/cron
      - ./student_private.pem:/app/student_private.pem:ro
      - ./student_public.pem:/app/student_public.pem:ro
      - ./instructor_public.pem:/app/instructor_public.pem:ro
      - ./api_response.json:/app/api_response.json:ro
    restart: unless-stopped

volumes:
  seed-data:
  cron-output:
